### PR TITLE
Fix metadata provider test for l2go

### PR DESCRIPTION
**Pull request by JanGut**

### CODE REVIEW

**Comment by JanGut** [comment]
It seems like, they have also changed the dom of l2go...

**Comment by Flova** [comment]
I don't think so because the tests work if I rerun them manually.

**Comment by Flova** [comment]
I think the server is down at the scheduled time or some thing like that.

**Review by timonegk — COMMENTED** [review]
The change seems to be wrong, when I open the page in a browser, the creator link contains spaces, not plus signs.

**Comment by Flova** [comment]
I close this pull request because it does not seem to work and the failing CI has most certainly some other reasons.
Feel free to reopen this pr if there are any additions to this.

**Comment by Flova** [comment]
The debugging added in pull request #111 resulted in the realization, that this pull request is still relevant but not complete.
More of that in issue #113

**Comment by Flova** [comment]
This pull request is obsolete due to pull request #114

**Comment by Flova** [comment]
Sorry for the mails, I thought I accidentally closed the issue but that was wrong.

**Pull request closed without merging**
